openapi: 3.1.0
info:
  title: スコア評価Bot API
  description: 投資判断スコアを返すAPI。RSI, VIXなどを元に総合スコアとコメントを返します。
  version: 1.0.0
servers:
  - url: https://score-bot-api.onrender.com

paths:
  /score:
    post:
      summary: 市場情報からスコア評価を取得する
      operationId: getScore
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                spy:
                  type: number
                qqq:
                  type: number
                vix:
                  type: number
                usd_jpy:
                  type: number
                rsi:
                  type: number
                volume_ratio:
                  type: number
                ma_break:
                  type: boolean
                roe:
                  type: number
                profit_margin:
                  type: number
              required:
                - spy
                - qqq
                - vix
                - usd_jpy
                - rsi
                - volume_ratio
                - ma_break
                - roe
                - profit_margin
      responses:
        "200":
          description: 正常にスコアが返されたとき
          content:
            application/json:
              schema:
                type: object
                properties:
                  score:
                    type: number
                  comments:
                    type: array
                    items:
                      type: string
                  judgment:
                    type: string

  /save_judgment:
    post:
      summary: 判断結果を記憶に保存する
      operationId: saveJudgment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
                result:
                  type: string
              required:
                - input
                - result
      responses:
        "200":
          description: 記録完了メッセージ
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /function_call:
    post:
      operationId: function_call
      summary: 決まった関数を呼び出します
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                function:
                  type: string
                  example: evaluate_market_conditions
                args:
                  type: object
                  properties:
                    spy:
                      type: number
                      example: 1.2
                    rsi:
                      type: number
                      example: 29
                    vix:
                      type: number
                      example: 18
      responses:
        '200':
          description: 成功時の応答
